blog/urls.py
from django.urls import path 
from . import views
from .feeds import LatestPostsFeed

app_name = 'blog'

urlpatterns = [
    path('post_list/<slug:tag_slug>/', views.PostList.as_view(), name='post-list-with-tagging'),
    path('post_list/', views.PostList.as_view(), name='post-list'),
    path('post_detail/<int:year>/<int:month>/<int:day>/<slug:post>',
        views.post_detail,
        name='post-detail'
    ),
    path('<int:post_id>/share/',
        views.post_share,
        name='post-share'
    ),
    path('feed/', LatestPostsFeed(), name='blog-feed'),
    path('search/', views.post_search, name='post-search'),
    path('search_2/', views.post_search_2, name='post-search-2'),
    path('search_3/', views.post_search_3, name='post-search-3'),
    path('search_4/', views.post_search_4, name='post-search-4'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

# add sitemap ulrs
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap
sitemaps = {
    'posts':PostSitemap,
    
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    #xml path 
    path('sitemap.xml', sitemap, {'sitemaps':sitemaps},
        name='django.contrib.sitemaps.views.sitemap')


    
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse

from taggit.managers import TaggableManager

class PublishedManager(models.Manager):
    """ custom post manager to filter data by status """
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')

    def searchBody(self, *args, **kwargs):
        pass

    def similar_posts(self, post_id):
        post = self.get_queryset().get(id = post_id)
        tags_list = post.tags.values_list('id', flat=True)
        similar_posts = self.get_queryset().filter(tags__in=tags_list).\
            exclude(id=post.id)
        similar_posts = similar_posts.annotate(tags_count = models.Count('tags')).\
             order_by('-tags_count', '-published')

        return similar_posts

class Postable(models.Model):
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

class Post(Postable):
    """  A post model class to create blog posts """
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    objects = models.Manager()  # The default manager.
    publishedPosts = PublishedManager()  # Our custom manager.
    
    title = models.CharField(max_length=264)
    slug = models.SlugField(max_length=264, unique_for_date='published')
    author = models.ForeignKey(User, on_delete=models.CASCADE ,
                                related_name='blog_posts')
    published = models.DateTimeField(default=timezone.now)
    status = models.CharField(max_length = 16,
                              choices=STATUS_CHOICES,
                              default = 'draft')
    tags = TaggableManager()

    class Meta:
        ordering = ('-published',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post-detail',
                        args = [
                            self.published.year,
                            self.published.month,
                            self.published.day,
                            self.slug
                        ]
        )
                           
    
class Comment(Postable):
    post = models.ForeignKey(Post, on_delete=models.CASCADE,
                             related_name= 'comments')
    name = models.CharField(max_length=254)
    email = models.EmailField()
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)
    
    def __str__(self):
        return f'Comment by{self.name} on {self.post} '
    

blog/forms.py
from django import forms
from .models import Comment

class EmailPostForm(forms.Form):
    name = forms.CharField(label ='your name' ,max_length=264)
    sender = forms.EmailField(label='your email')
    receiver = forms.EmailField(label='reciver email')
    comments = forms.CharField(label='any comments?',
                                required = False,
                                widget=forms.Textarea)                       
            
    

class CommentPostForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email','body')
    

class SearchForm(forms.Form):
    """  allow users search using the postgres full search """
    query = forms.CharField()

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView
from django.core.mail import send_mail
from django.contrib.postgres.search import SearchQuery, SearchRank, SearchVector, TrigramSimilarity


from .models import Post, Comment
from .forms import  EmailPostForm, CommentPostForm,\
                    SearchForm


from taggit.models import Tag
class PostList(ListView):
    queryset = Post.publishedPosts.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'blog/post/list.html'

    def get_queryset(self):
        tag_slug = self.kwargs.get('tag_slug', None)
       
        if tag_slug :
            self.tag = get_object_or_404(Tag, slug =tag_slug )
            self.queryset = self.queryset.filter(tags__in = [self.tag])
        return self.queryset
    
    def get_context_data(self, **kwargs):
        context =  super().get_context_data(**kwargs)
        try :
            context['tag'] = self.tag 
        except :
           context['tag'] = None
        return context
    

def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post,
                            slug = post,
                            status= 'published',
                            published__year = year,
                            published__month = month,
                            published__day = day,

    )
    #List of active comments 
    comments = post.comments.filter(active=True)
    new_comment = None
    
    if request.method == 'POST':
        # validate data 
        comment_form = CommentPostForm(request.POST)
        
        if comment_form.is_valid():
            # print(comment_form.cleaned_data)
            # print(request.POST)
            # create but do not save to the db
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            #save to the db 
            new_comment.save()
            comment_form = CommentPostForm()
    else:
        comment_form = CommentPostForm()
    # get similar posts to recommend to the user 
    # see how the query is converted to sql 
    # last 4 posts ordered by tags_count and published date
    similar_posts = Post.publishedPosts.similar_posts(post.id)[:4]
    # print(similar_post.query)                
    return render(request, 'blog/post/detail.html',
                 {
                    'post':post,
                    'comment_form':comment_form,
                    'new_comment':new_comment,
                     'comments':comments,
                     'similar_posts':similar_posts,
                 })



def post_share(request, post_id: int) :
    post = get_object_or_404(Post, id = post_id, status='published')
    send = False
    # 2 possible http actions  get or post
    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        
        if form.is_valid():
            # cleaned data allways contains 
            # the valid data only 

            cd = form.cleaned_data
            #send email
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f'{cd["name"]} recommends you read {post.title}'
            message = f'Read {post.title} at {post_url}\n\n'\
                      f'{cd["name"]}\'s comments: {cd["comments"]}'
            
            send_mail(subject, message,'omarahmed010052@gmail',[cd['receiver']])
            send = True

        # else if not valid 
        # return http response with form.errors

            
    else:
        form = EmailPostForm()
    return render(request, 'blog/post/share.html',{
                    'post':post,
                    'form':form,
                    'sent':send,
                    })



def post_search(request):
    form = SearchForm()
    query = None
    results = []

    if "query" in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            results = Post.objects.annotate(
                search = SearchVector('title', 'body')
            ).filter(search = query)
        
    return render(request,
                  'blog/post/search.html',
                  {'form':form,
                  'query': query,
                  'results':results,
                  }  
                    )


def post_search_3(request):
    """another way of searching using ranking and weighting  """
    form = SearchForm()
    query = None
    results = []

    if "query" in request.GET:
        form = SearchForm(request.GET)
       
        if form.is_valid():
            query = form.cleaned_data['query']
            search_vector = SearchVector('title', weight= 'A') +\
                            SearchVector('body', weight='B')
                        
            search_query = SearchQuery(query)
            results = Post.objects.annotate(
               
                rank = SearchRank(search_vector, search_query)
            ).filter(rank__gte = .3).order_by('-rank')
    
        
    return render(request,
                  'blog/post/search.html',
                  {'form':form,
                  'query': query,
                  'results':results,
                  }  
                    )


def post_search_2(request):
    """another way of searching using ranking  """
    form = SearchForm()
    query = None
    results = []

    if "query" in request.GET:
        form = SearchForm(request.GET)
       
        if form.is_valid():
            query = form.cleaned_data['query']
            search_vector = SearchVector('title', 'body')
            search_query = SearchQuery(query)
            results = Post.objects.annotate(
                search=search_vector,
                rank = SearchRank(search_vector, search_query)
            ).filter(search = search_query).order_by('-rank')
    
        
    return render(request,
                  'blog/post/search.html',
                  {'form':form,
                  'query': query,
                  'results':results,
                  }  
                    )

def post_search_4(request):
    """another way of searching using trigram similarty  """
    form = SearchForm()
    query = None
    results = []

    if "query" in request.GET:
        form = SearchForm(request.GET)
       
        if form.is_valid():
            query = form.cleaned_data['query']
            # search_vector = SearchVector('title', 'body')
            search_query = SearchQuery(query)
            results = Post.objects.annotate(
                similarity=TrigramSimilarity('title', query)
            ).filter(similarity__gt=0.1).order_by('-similarity')
    
        
    return render(request,
                  'blog/post/search.html',
                  {'form':form,
                  'query': query,
                  'results':results,
                  }  
                    )

blog/templates/blog/post/detail.html
{% extends 'blog/base.html' %}
{% load blog_tags %}

{% block title%} {{post.title}} {% endblock %}

{% block content %}
 <h1> {{post.title}} </h1>
    <p class="date">
        Published {{ post.published }} by {{ post.author }}
    </p>
    {{post.body|markdown }}
    <p>
        <a href="{%url 'blog:post-share' post.id %}">
            Share Post
        </a>

        <a href="{%url 'blog:post-list' %}">
           return 
        </a>
    </p>
    <h2>Similar Posts </h2>
    {%for post in similar_posts %}
        <p>
            <a href="{{ post.get_absolute_url }}">
                {{post.title}}
            </a>
        </p>
    {%empty %}
        There are No similar posts, sorry.
    {%endfor%}

    {% with comments.count as total_comments %}
        <h2>
            {{total_comments}} comment{{total_comments|pluralize}}

        </h2>
    {% endwith %}
    {% for comment in comments %}
        <div class="comment">
            <p class='info'>
                comment {{forloop.counter}} by {{comment.name }}
                {{comment.created }}
            </p>
            {{comment.body|linebreaks}}
        </div>
    {% empty %}
        <p>There are no comments yet.</p>
    {% endfor %}
    
    {%if new_comment %}
        <h2 class="success">Your comment has been added.</h2>
    {%endif%}
    <h2>Add a new comment</h2>
    <form method="POST">
        {% csrf_token %}
        {{comment_form.as_p}}
        <p>
            <input type="submit" value="Add comment">
        </p>
    </form>    
    
{% endblock %}

blog/templates/blog/post/latest_posts.html
<ul>
    {% for post in latest_posts %}
       <li>
            <a href="{{ post.get_absolute_url }}">
                {{post.title}}
            </a>
       </li>
    {%endfor%}
</ul>

blog/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% load blog_tags %}

{% block title %} My Blog {% endblock %}

{%block content %}
    <h1> My Blog</h1>
    {% if tag %}
    <h2>Posts tagged with "{{ tag.name }}"</h2>
    {% endif %}
    {% for post in posts %}
        <h2>
            <a href="{{ post.get_absolute_url }}">
                {{post.title}}
            </a>
           
        </h2>
        <p class='tags'>
            {%for tag in post.tags.all %}
                <a href="{% url 'blog:post-list-with-tagging' tag.slug %}">
                    {{tag.name}}
                </a>
                {% if not forloop.last %}, {% endif %}
            {%endfor %}

        </p>
        <p class="date">
            Published {{ post.published }} by {{ post.author }}
        </p>
        {{ post.body|markdown|truncatewords_html:30}}
    {%endfor%}
    {% include 'pagination.html' with page=page_obj %}
{% endblock %}

blog/templates/blog/post/search.html
{% extends "blog/base.html" %}
{% load blog_tags %}

{% block title %}Search{% endblock %}

{% block content %}
{% if query %}
<h1>Posts containing "{{ query }}"</h1>
<h3>
    {% with results.count as total_results %}
    Found {{ total_results }} result{{ total_results|pluralize }}
    {% endwith %}
</h3>
{% for post in results %}

    <h4>
  
    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h4>
    {{ post.body|markdown|truncatewords_html:5 }}
{% empty %}
<p>There are no results for your query.</p>
{% endfor %}
<p><a href="{% url "blog:post-search" %}">Search again</a></p>
{% else %}
<h1>Search for posts</h1>
<form method="get">
    {{ form.as_p }}
    <input type="submit" value="Search">
</form>
{% endif %}
{% endblock %}

blog/templates/blog/post/share.html
{% extends 'blog/base.html' %}
{%block title %} Share Post {%endblock %}


{%block content %}
    {%if sent %}
        <h1>E-mail successfully sent</h1>
        <p>
            "{{ post.title }}" was successfully sent to {{form.cleaned_data.receiver}}
            
        </p>
    {%else %}
        <h1>Share" {{post.title}}" by e-mail</h1>
        <form method="post">
            {{form.as_p}}
            {% csrf_token %}
            <input type="submit" value="send e-mail">
        </form>
    {%endif%}
{%endblock %}